- hosts: deep_learning
  become: True
  vars:
    cafe_git_repo_url: github.com/BVLC/caffe.git
   
  tasks:
    - git: repo="git://{{ cafe_git_repo_url }}"
           dest=~/caffe
    
    - apt: name={{item}} state=present
      with_items: 
        - build-essential 
        - cmake 
        - git
        - build-essential
        - pkg-config
        - unzip
        - ffmpeg
        - qtbase5-dev
        - python-dev
        - python3-dev
        - python-numpy
        - python3-numpy
        - libopencv-dev
        - libgtk-3-dev
        - libdc1394-22
        - libdc1394-22-dev                          
        - libjpeg-dev
        - libpng12-dev
        - libtiff5-dev
        - libjasper-dev
        - libavcodec-dev
        - libavformat-dev
        - libswscale-dev
        - libxine2-dev
        - libgstreamer0.10-dev
        - libgstreamer-plugins-base0.10-dev
        - libv4l-dev
        - libtbb-dev
        - libfaac-dev
        - libmp3lame-dev
        - libopencore-amrnb-dev
        - libopencore-amrwb-dev          
        - libtheora-dev
        - libvorbis-dev
        - libxvidcore-dev
        - v4l-utils          
        - libprotobuf-dev
        - libleveldb-dev
        - libsnappy-dev
        - libopencv-dev
        - libhdf5-serial-dev
        - protobuf-compiler

    - apt: 
        name: libboost-all-dev 
        state: present
        install_recommends: no

    - apt: update_cache=yes  force=yes
     
    - shell: cd ~/caffe && cp Makefile.config.example Makefile.config
            
        